# Generated by Django 4.2 on 2023-04-13 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_car_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_1', models.ImageField(blank=True, upload_to='images')),
                ('image_2', models.ImageField(blank=True, upload_to='images')),
                ('image_3', models.ImageField(blank=True, upload_to='images')),
                ('image_4', models.ImageField(blank=True, upload_to='images')),
                ('image_5', models.ImageField(blank=True, upload_to='images')),
                ('image_6', models.ImageField(blank=True, upload_to='images')),
                ('image_7', models.ImageField(blank=True, upload_to='images')),
                ('image_8', models.ImageField(blank=True, upload_to='images')),
                ('image_9', models.ImageField(blank=True, upload_to='images')),
                ('image_10', models.ImageField(blank=True, upload_to='images')),
                ('image_11', models.ImageField(blank=True, upload_to='images')),
                ('image_12', models.ImageField(blank=True, upload_to='images')),
                ('image_13', models.ImageField(blank=True, upload_to='images')),
                ('image_14', models.ImageField(blank=True, upload_to='images')),
                ('image_15', models.ImageField(blank=True, upload_to='images')),
                ('image_16', models.ImageField(blank=True, upload_to='images')),
                ('image_17', models.ImageField(blank=True, upload_to='images')),
                ('image_18', models.ImageField(blank=True, upload_to='images')),
                ('image_19', models.ImageField(blank=True, upload_to='images')),
                ('image_20', models.ImageField(blank=True, upload_to='images')),
            ],
        ),
        migrations.AlterField(
            model_name='car',
            name='images',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.image'),
        ),
    ]
