# Generated by Django 4.2 on 2023-04-13 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_image_alter_car_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='price',
            field=models.CharField(default=3, max_length=250),
            preserve_default=False,
        ),
    ]
