# Generated by Django 4.2 on 2023-04-20 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_car_month_alter_car_yom'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='is_reserved',
            field=models.BooleanField(default=False, verbose_name='Reserved'),
        ),
        migrations.AddField(
            model_name='car',
            name='is_sold',
            field=models.BooleanField(default=False, verbose_name='Sold'),
        ),
    ]
